<style>
    ul.fe-icons {
        margin-left: 0;
        padding-left: 0;
    }
    ul.fe-icons li {
        list-style-type: none;
    }
</style>

<h2>Navigation Icons</h2>
<ul class="fe-icons">
    <li><i aria-hidden="true" class="fe arrow_up"></i> fe arrow_up</li>
    <li><i aria-hidden="true" class="fe arrow_down"></i> fe arrow_down</li>
    <li><i aria-hidden="true" class="fe arrow_left"></i> fe arrow_left</li>
    <li><i aria-hidden="true" class="fe arrow_right"></i> fe arrow_right</li>
    <li><i aria-hidden="true" class="fe arrow_left-up"></i> fe arrow_left-up</li>
    <li><i aria-hidden="true" class="fe arrow_right-up"></i> fe arrow_right-up</li>
    <li><i aria-hidden="true" class="fe arrow_right-down"></i> fe arrow_right-down</li>
    <li><i aria-hidden="true" class="fe arrow_left-down"></i> fe arrow_left-down</li>
    <li><i aria-hidden="true" class="fe arrow-up-down"></i> fe arrow-up-down</li>
    <li><i aria-hidden="true" class="fe arrow_up-down_alt"></i> fe arrow_up-down_alt</li>
    <li><i aria-hidden="true" class="fe arrow_left-right_alt"></i> fe arrow_left-right_alt</li>
    <li><i aria-hidden="true" class="fe arrow_left-right"></i> fe arrow_left-right</li>
    <li><i aria-hidden="true" class="fe arrow_expand_alt2"></i> fe arrow_expand_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_expand_alt"></i> fe arrow_expand_alt</li>
    <li><i aria-hidden="true" class="fe arrow_condense"></i> fe arrow_condense</li>
    <li><i aria-hidden="true" class="fe arrow_expand"></i> fe arrow_expand</li>
    <li><i aria-hidden="true" class="fe arrow_move"></i> fe arrow_move</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-up"></i> fe arrow_carrot-up</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-down"></i> fe arrow_carrot-down</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-left"></i> fe arrow_carrot-left</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-right"></i> fe arrow_carrot-right</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2up"></i> fe arrow_carrot-2up</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2down"></i> fe arrow_carrot-2down</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2left"></i> fe arrow_carrot-2left</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2right"></i> fe arrow_carrot-2right</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-up_alt2"></i> fe arrow_carrot-up_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-down_alt2"></i> fe arrow_carrot-down_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-left_alt2"></i> fe arrow_carrot-left_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-right_alt2"></i> fe arrow_carrot-right_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2up_alt2"></i> fe arrow_carrot-2up_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2down_alt2"></i> fe arrow_carrot-2down_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2left_alt2"></i> fe arrow_carrot-2left_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2right_alt2"></i> fe arrow_carrot-2right_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-up"></i> fe arrow_triangle-up</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-down"></i> fe arrow_triangle-down</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-left"></i> fe arrow_triangle-left</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-right"></i> fe arrow_triangle-right</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-up_alt2"></i> fe arrow_triangle-up_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-down_alt2"></i> fe arrow_triangle-down_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-left_alt2"></i> fe arrow_triangle-left_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-right_alt2"></i> fe arrow_triangle-right_alt2</li>
    <li><i aria-hidden="true" class="fe arrow_back"></i> fe arrow_back</li>
    <li><i aria-hidden="true" class="fe arrow_up_alt"></i> fe arrow_up_alt</li>
    <li><i aria-hidden="true" class="fe arrow_down_alt"></i> fe arrow_down_alt</li>
    <li><i aria-hidden="true" class="fe arrow_left_alt"></i> fe arrow_left_alt</li>
    <li><i aria-hidden="true" class="fe arrow_right_alt"></i> fe arrow_right_alt</li>
    <li><i aria-hidden="true" class="fe arrow_left-up_alt"></i> fe arrow_left-up_alt</li>
    <li><i aria-hidden="true" class="fe arrow_right-up_alt"></i> fe arrow_right-up_alt</li>
    <li><i aria-hidden="true" class="fe arrow_right-down_alt"></i> fe arrow_right-down_alt</li>
    <li><i aria-hidden="true" class="fe arrow_left-down_alt"></i> fe arrow_left-down_alt</li>
    <li><i aria-hidden="true" class="fe arrow_condense_alt"></i> fe arrow_condense_alt</li>
    <li><i aria-hidden="true" class="fe arrow_expand_alt3"></i> fe arrow_expand_alt3</li>
    <li><i aria-hidden="true" class="fe arrow_carrot_up_alt"></i> fe arrow_carrot_up_alt</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-down_alt"></i> fe arrow_carrot-down_alt</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-left_alt"></i> fe arrow_carrot-left_alt</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-right_alt"></i> fe arrow_carrot-right_alt</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2up_alt"></i> fe arrow_carrot-2up_alt</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2dwnn_alt"></i> fe arrow_carrot-2dwnn_alt</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2left_alt"></i> fe arrow_carrot-2left_alt</li>
    <li><i aria-hidden="true" class="fe arrow_carrot-2right_alt"></i> fe arrow_carrot-2right_alt</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-up_alt"></i> fe arrow_triangle-up_alt</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-down_alt"></i> fe arrow_triangle-down_alt</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-left_alt"></i> fe arrow_triangle-left_alt</li>
    <li><i aria-hidden="true" class="fe arrow_triangle-right_alt"></i> fe arrow_triangle-right_alt</li>
</ul>

<h2>Web Icons</h2>
<ul class="fe-icons">
    <li><i aria-hidden="true" class="fe icon_minus-06"></i> fe icon_minus-06</li>
    <li><i aria-hidden="true" class="fe icon_plus"></i> fe icon_plus</li>
    <li><i aria-hidden="true" class="fe icon_close"></i> fe icon_close</li>
    <li><i aria-hidden="true" class="fe icon_check"></i> fe icon_check</li>
    <li><i aria-hidden="true" class="fe icon_minus_alt2"></i> fe icon_minus_alt2</li>
    <li><i aria-hidden="true" class="fe icon_plus_alt2"></i> fe icon_plus_alt2</li>
    <li><i aria-hidden="true" class="fe icon_close_alt2"></i> fe icon_close_alt2</li>
    <li><i aria-hidden="true" class="fe icon_check_alt2"></i> fe icon_check_alt2</li>
    <li><i aria-hidden="true" class="fe icon_zoom-out_alt"></i> fe icon_zoom-out_alt</li>
    <li><i aria-hidden="true" class="fe icon_zoom-in_alt"></i> fe icon_zoom-in_alt</li>
    <li><i aria-hidden="true" class="fe icon_search"></i> fe icon_search</li>
    <li><i aria-hidden="true" class="fe icon_box-empty"></i> fe icon_box-empty</li>
    <li><i aria-hidden="true" class="fe icon_box-selected"></i> fe icon_box-selected</li>
    <li><i aria-hidden="true" class="fe icon_minus-box"></i> fe icon_minus-box</li>
    <li><i aria-hidden="true" class="fe icon_plus-box"></i> fe icon_plus-box</li>
    <li><i aria-hidden="true" class="fe icon_box-checked"></i> fe icon_box-checked</li>
    <li><i aria-hidden="true" class="fe icon_circle-empty"></i> fe icon_circle-empty</li>
    <li><i aria-hidden="true" class="fe icon_circle-slelected"></i> fe icon_circle-slelected</li>
    <li><i aria-hidden="true" class="fe icon_stop_alt2"></i> fe icon_stop_alt2</li>
    <li><i aria-hidden="true" class="fe icon_stop"></i> fe icon_stop</li>
    <li><i aria-hidden="true" class="fe icon_pause_alt2"></i> fe icon_pause_alt2</li>
    <li><i aria-hidden="true" class="fe icon_pause"></i> fe icon_pause</li>
    <li><i aria-hidden="true" class="fe icon_menu"></i> fe icon_menu</li>
    <li><i aria-hidden="true" class="fe icon_menu-square_alt2"></i> fe icon_menu-square_alt2</li>
    <li><i aria-hidden="true" class="fe icon_menu-circle_alt2"></i> fe icon_menu-circle_alt2</li>
    <li><i aria-hidden="true" class="fe icon_ul"></i> fe icon_ul</li>
    <li><i aria-hidden="true" class="fe icon_ol"></i> fe icon_ol</li>
    <li><i aria-hidden="true" class="fe icon_adjust-horiz"></i> fe icon_adjust-horiz</li>
    <li><i aria-hidden="true" class="fe icon_adjust-vert"></i> fe icon_adjust-vert</li>
    <li><i aria-hidden="true" class="fe icon_document_alt"></i> fe icon_document_alt</li>
    <li><i aria-hidden="true" class="fe icon_documents_alt"></i> fe icon_documents_alt</li>
    <li><i aria-hidden="true" class="fe icon_pencil"></i> fe icon_pencil</li>
    <li><i aria-hidden="true" class="fe icon_pencil-edit_alt"></i> fe icon_pencil-edit_alt</li>
    <li><i aria-hidden="true" class="fe icon_pencil-edit"></i> fe icon_pencil-edit</li>
    <li><i aria-hidden="true" class="fe icon_folder-alt"></i> fe icon_folder-alt</li>
    <li><i aria-hidden="true" class="fe icon_folder-open_alt"></i> fe icon_folder-open_alt</li>
    <li><i aria-hidden="true" class="fe icon_folder-add_alt"></i> fe icon_folder-add_alt</li>
    <li><i aria-hidden="true" class="fe icon_info_alt"></i> fe icon_info_alt</li>
    <li><i aria-hidden="true" class="fe icon_error-oct_alt"></i> fe icon_error-oct_alt</li>
    <li><i aria-hidden="true" class="fe icon_error-circle_alt"></i> fe icon_error-circle_alt</li>
    <li><i aria-hidden="true" class="fe icon_error-triangle_alt"></i> fe icon_error-triangle_alt</li>
    <li><i aria-hidden="true" class="fe icon_question_alt2"></i> fe icon_question_alt2</li>
    <li><i aria-hidden="true" class="fe icon_question"></i> fe icon_question</li>
    <li><i aria-hidden="true" class="fe icon_comment_alt"></i> fe icon_comment_alt</li>
    <li><i aria-hidden="true" class="fe icon_chat_alt"></i> fe icon_chat_alt</li>
    <li><i aria-hidden="true" class="fe icon_vol-mute_alt"></i> fe icon_vol-mute_alt</li>
    <li><i aria-hidden="true" class="fe icon_volume-low_alt"></i> fe icon_volume-low_alt</li>
    <li><i aria-hidden="true" class="fe icon_volume-high_alt"></i> fe icon_volume-high_alt</li>
    <li><i aria-hidden="true" class="fe icon_quotations"></i> fe icon_quotations</li>
    <li><i aria-hidden="true" class="fe icon_quotations_alt2"></i> fe icon_quotations_alt2</li>
    <li><i aria-hidden="true" class="fe icon_clock_alt"></i> fe icon_clock_alt</li>
    <li><i aria-hidden="true" class="fe icon_lock_alt"></i> fe icon_lock_alt</li>
    <li><i aria-hidden="true" class="fe icon_lock-open_alt"></i> fe icon_lock-open_alt</li>
    <li><i aria-hidden="true" class="fe icon_key_alt"></i> fe icon_key_alt</li>
    <li><i aria-hidden="true" class="fe icon_cloud_alt"></i> fe icon_cloud_alt</li>
    <li><i aria-hidden="true" class="fe icon_cloud-upload_alt"></i> fe icon_cloud-upload_alt</li>
    <li><i aria-hidden="true" class="fe icon_cloud-download_alt"></i> fe icon_cloud-download_alt</li>
    <li><i aria-hidden="true" class="fe icon_image"></i> fe icon_image</li>
    <li><i aria-hidden="true" class="fe icon_images"></i> fe icon_images</li>
    <li><i aria-hidden="true" class="fe icon_lightbulb_alt"></i> fe icon_lightbulb_alt</li>
    <li><i aria-hidden="true" class="fe icon_gift_alt"></i> fe icon_gift_alt</li>
    <li><i aria-hidden="true" class="fe icon_house_alt"></i> fe icon_house_alt</li>
    <li><i aria-hidden="true" class="fe icon_genius"></i> fe icon_genius</li>
    <li><i aria-hidden="true" class="fe icon_mobile"></i> fe icon_mobile</li>
    <li><i aria-hidden="true" class="fe icon_tablet"></i> fe icon_tablet</li>
    <li><i aria-hidden="true" class="fe icon_laptop"></i> fe icon_laptop</li>
    <li><i aria-hidden="true" class="fe icon_desktop"></i> fe icon_desktop</li>
    <li><i aria-hidden="true" class="fe icon_camera_alt"></i> fe icon_camera_alt</li>
    <li><i aria-hidden="true" class="fe icon_mail_alt"></i> fe icon_mail_alt</li>
    <li><i aria-hidden="true" class="fe icon_cone_alt"></i> fe icon_cone_alt</li>
    <li><i aria-hidden="true" class="fe icon_ribbon_alt"></i> fe icon_ribbon_alt</li>
    <li><i aria-hidden="true" class="fe icon_bag_alt"></i> fe icon_bag_alt</li>
    <li><i aria-hidden="true" class="fe icon_creditcard"></i> fe icon_creditcard</li>
    <li><i aria-hidden="true" class="fe icon_cart_alt"></i> fe icon_cart_alt</li>
    <li><i aria-hidden="true" class="fe icon_paperclip"></i> fe icon_paperclip</li>
    <li><i aria-hidden="true" class="fe icon_tag_alt"></i> fe icon_tag_alt</li>
    <li><i aria-hidden="true" class="fe icon_tags_alt"></i> fe icon_tags_alt</li>
    <li><i aria-hidden="true" class="fe icon_trash_alt"></i> fe icon_trash_alt</li>
    <li><i aria-hidden="true" class="fe icon_cursor_alt"></i> fe icon_cursor_alt</li>
    <li><i aria-hidden="true" class="fe icon_mic_alt"></i> fe icon_mic_alt</li>
    <li><i aria-hidden="true" class="fe icon_compass_alt"></i> fe icon_compass_alt</li>
    <li><i aria-hidden="true" class="fe icon_pin_alt"></i> fe icon_pin_alt</li>
    <li><i aria-hidden="true" class="fe icon_pushpin_alt"></i> fe icon_pushpin_alt</li>
    <li><i aria-hidden="true" class="fe icon_map_alt"></i> fe icon_map_alt</li>
    <li><i aria-hidden="true" class="fe icon_drawer_alt"></i> fe icon_drawer_alt</li>
    <li><i aria-hidden="true" class="fe icon_toolbox_alt"></i> fe icon_toolbox_alt</li>
    <li><i aria-hidden="true" class="fe icon_book_alt"></i> fe icon_book_alt</li>
    <li><i aria-hidden="true" class="fe icon_calendar"></i> fe icon_calendar</li>
    <li><i aria-hidden="true" class="fe icon_film"></i> fe icon_film</li>
    <li><i aria-hidden="true" class="fe icon_table"></i> fe icon_table</li>
    <li><i aria-hidden="true" class="fe icon_contacts_alt"></i> fe icon_contacts_alt</li>
    <li><i aria-hidden="true" class="fe icon_headphones"></i> fe icon_headphones</li>
    <li><i aria-hidden="true" class="fe icon_lifesaver"></i> fe icon_lifesaver</li>
    <li><i aria-hidden="true" class="fe icon_piechart"></i> fe icon_piechart</li>
    <li><i aria-hidden="true" class="fe icon_refresh"></i> fe icon_refresh</li>
    <li><i aria-hidden="true" class="fe icon_link_alt"></i> fe icon_link_alt</li>
    <li><i aria-hidden="true" class="fe icon_link"></i> fe icon_link</li>
    <li><i aria-hidden="true" class="fe icon_loading"></i> fe icon_loading</li>
    <li><i aria-hidden="true" class="fe icon_blocked"></i> fe icon_blocked</li>
    <li><i aria-hidden="true" class="fe icon_archive_alt"></i> fe icon_archive_alt</li>
    <li><i aria-hidden="true" class="fe icon_heart_alt"></i> fe icon_heart_alt</li>
    <li><i aria-hidden="true" class="fe icon_printer"></i> fe icon_printer</li>
    <li><i aria-hidden="true" class="fe icon_calulator"></i> fe icon_calulator</li>
    <li><i aria-hidden="true" class="fe icon_building"></i> fe icon_building</li>
    <li><i aria-hidden="true" class="fe icon_floppy"></i> fe icon_floppy</li>
    <li><i aria-hidden="true" class="fe icon_drive"></i> fe icon_drive</li>
    <li><i aria-hidden="true" class="fe icon_search-2"></i> fe icon_search-2</li>
    <li><i aria-hidden="true" class="fe icon_id"></i> fe icon_id</li>
    <li><i aria-hidden="true" class="fe icon_id-2"></i> fe icon_id-2</li>
    <li><i aria-hidden="true" class="fe icon_puzzle"></i> fe icon_puzzle</li>
    <li><i aria-hidden="true" class="fe icon_like"></i> fe icon_like</li>
    <li><i aria-hidden="true" class="fe icon_dislike"></i> fe icon_dislike</li>
    <li><i aria-hidden="true" class="fe icon_mug"></i> fe icon_mug</li>
    <li><i aria-hidden="true" class="fe icon_currency"></i> fe icon_currency</li>
    <li><i aria-hidden="true" class="fe icon_wallet"></i> fe icon_wallet</li>
    <li><i aria-hidden="true" class="fe icon_pens"></i> fe icon_pens</li>
    <li><i aria-hidden="true" class="fe icon_easel"></i> fe icon_easel</li>
    <li><i aria-hidden="true" class="fe icon_flowchart"></i> fe icon_flowchart</li>
    <li><i aria-hidden="true" class="fe icon_datareport"></i> fe icon_datareport</li>
    <li><i aria-hidden="true" class="fe icon_briefcase"></i> fe icon_briefcase</li>
    <li><i aria-hidden="true" class="fe icon_shield"></i> fe icon_shield</li>
    <li><i aria-hidden="true" class="fe icon_percent"></i> fe icon_percent</li>
    <li><i aria-hidden="true" class="fe icon_globe"></i> fe icon_globe</li>
    <li><i aria-hidden="true" class="fe icon_globe-2"></i> fe icon_globe-2</li>
    <li><i aria-hidden="true" class="fe icon_target"></i> fe icon_target</li>
    <li><i aria-hidden="true" class="fe icon_hourglass"></i> fe icon_hourglass</li>
    <li><i aria-hidden="true" class="fe icon_star_alt"></i> fe icon_star_alt</li>
    <li><i aria-hidden="true" class="fe icon_star-half_alt"></i> fe icon_star-half_alt</li>
    <li><i aria-hidden="true" class="fe icon_star"></i> fe icon_star</li>
    <li><i aria-hidden="true" class="fe icon_star-half"></i> fe icon_star-half</li>
    <li><i aria-hidden="true" class="fe icon_tools"></i> fe icon_tools</li>
    <li><i aria-hidden="true" class="fe icon_tool"></i> fe icon_tool</li>
    <li><i aria-hidden="true" class="fe icon_cog"></i> fe icon_cog</li>
    <li><i aria-hidden="true" class="fe icon_cogs"></i> fe icon_cogs</li>
    <li><i aria-hidden="true" class="fe icon_minus_alt"></i> fe icon_minus_alt</li>
    <li><i aria-hidden="true" class="fe icon_plus_alt"></i> fe icon_plus_alt</li>
    <li><i aria-hidden="true" class="fe icon_close_alt"></i> fe icon_close_alt</li>
    <li><i aria-hidden="true" class="fe icon_check_alt"></i> fe icon_check_alt</li>
    <li><i aria-hidden="true" class="fe icon_zoom-out"></i> fe icon_zoom-out</li>
    <li><i aria-hidden="true" class="fe icon_zoom-in"></i> fe icon_zoom-in</li>
    <li><i aria-hidden="true" class="fe icon_stop_alt"></i> fe icon_stop_alt</li>
    <li><i aria-hidden="true" class="fe icon_menu-square_alt"></i> fe icon_menu-square_alt</li>
    <li><i aria-hidden="true" class="fe icon_menu-circle_alt"></i> fe icon_menu-circle_alt</li>
    <li><i aria-hidden="true" class="fe icon_document"></i> fe icon_document</li>
    <li><i aria-hidden="true" class="fe icon_documents"></i> fe icon_documents</li>
    <li><i aria-hidden="true" class="fe icon_pencil_alt"></i> fe icon_pencil_alt</li>
    <li><i aria-hidden="true" class="fe icon_folder"></i> fe icon_folder</li>
    <li><i aria-hidden="true" class="fe icon_folder-open"></i> fe icon_folder-open</li>
    <li><i aria-hidden="true" class="fe icon_folder-add"></i> fe icon_folder-add</li>
    <li><i aria-hidden="true" class="fe icon_folder_upload"></i> fe icon_folder_upload</li>
    <li><i aria-hidden="true" class="fe icon_folder_download"></i> fe icon_folder_download</li>
    <li><i aria-hidden="true" class="fe icon_info"></i> fe icon_info</li>
    <li><i aria-hidden="true" class="fe icon_error-circle"></i> fe icon_error-circle</li>
    <li><i aria-hidden="true" class="fe icon_error-oct"></i> fe icon_error-oct</li>
    <li><i aria-hidden="true" class="fe icon_error-triangle"></i> fe icon_error-triangle</li>
    <li><i aria-hidden="true" class="fe icon_question_alt"></i> fe icon_question_alt</li>
    <li><i aria-hidden="true" class="fe icon_comment"></i> fe icon_comment</li>
    <li><i aria-hidden="true" class="fe icon_chat"></i> fe icon_chat</li>
    <li><i aria-hidden="true" class="fe icon_vol-mute"></i> fe icon_vol-mute</li>
    <li><i aria-hidden="true" class="fe icon_volume-low"></i> fe icon_volume-low</li>
    <li><i aria-hidden="true" class="fe icon_volume-high"></i> fe icon_volume-high</li>
    <li><i aria-hidden="true" class="fe icon_quotations_alt"></i> fe icon_quotations_alt</li>
    <li><i aria-hidden="true" class="fe icon_clock"></i> fe icon_clock</li>
    <li><i aria-hidden="true" class="fe icon_lock"></i> fe icon_lock</li>
    <li><i aria-hidden="true" class="fe icon_lock-open"></i> fe icon_lock-open</li>
    <li><i aria-hidden="true" class="fe icon_key"></i> fe icon_key</li>
    <li><i aria-hidden="true" class="fe icon_cloud"></i> fe icon_cloud</li>
    <li><i aria-hidden="true" class="fe icon_cloud-upload"></i> fe icon_cloud-upload</li>
    <li><i aria-hidden="true" class="fe icon_cloud-download"></i> fe icon_cloud-download</li>
    <li><i aria-hidden="true" class="fe icon_lightbulb"></i> fe icon_lightbulb</li>
    <li><i aria-hidden="true" class="fe icon_gift"></i> fe icon_gift</li>
    <li><i aria-hidden="true" class="fe icon_house"></i> fe icon_house</li>
    <li><i aria-hidden="true" class="fe icon_camera"></i> fe icon_camera</li>
    <li><i aria-hidden="true" class="fe icon_mail"></i> fe icon_mail</li>
    <li><i aria-hidden="true" class="fe icon_cone"></i> fe icon_cone</li>
    <li><i aria-hidden="true" class="fe icon_ribbon"></i> fe icon_ribbon</li>
    <li><i aria-hidden="true" class="fe icon_bag"></i> fe icon_bag</li>
    <li><i aria-hidden="true" class="fe icon_cart"></i> fe icon_cart</li>
    <li><i aria-hidden="true" class="fe icon_tag"></i> fe icon_tag</li>
    <li><i aria-hidden="true" class="fe icon_tags"></i> fe icon_tags</li>
    <li><i aria-hidden="true" class="fe icon_trash"></i> fe icon_trash</li>
    <li><i aria-hidden="true" class="fe icon_cursor"></i> fe icon_cursor</li>
    <li><i aria-hidden="true" class="fe icon_mic"></i> fe icon_mic</li>
    <li><i aria-hidden="true" class="fe icon_compass"></i> fe icon_compass</li>
    <li><i aria-hidden="true" class="fe icon_pin"></i> fe icon_pin</li>
    <li><i aria-hidden="true" class="fe icon_pushpin"></i> fe icon_pushpin</li>
    <li><i aria-hidden="true" class="fe icon_map"></i> fe icon_map</li>
    <li><i aria-hidden="true" class="fe icon_drawer"></i> fe icon_drawer</li>
    <li><i aria-hidden="true" class="fe icon_toolbox"></i> fe icon_toolbox</li>
    <li><i aria-hidden="true" class="fe icon_book"></i> fe icon_book</li>
    <li><i aria-hidden="true" class="fe icon_contacts"></i> fe icon_contacts</li>
    <li><i aria-hidden="true" class="fe icon_archive"></i> fe icon_archive</li>
    <li><i aria-hidden="true" class="fe icon_heart"></i> fe icon_heart</li>
    <li><i aria-hidden="true" class="fe icon_profile"></i> fe icon_profile</li>
    <li><i aria-hidden="true" class="fe icon_group"></i> fe icon_group</li>
    <li><i aria-hidden="true" class="fe icon_grid-2x2"></i> fe icon_grid-2x2</li>
    <li><i aria-hidden="true" class="fe icon_grid-3x3"></i> fe icon_grid-3x3</li>
    <li><i aria-hidden="true" class="fe icon_music"></i> fe icon_music</li>
    <li><i aria-hidden="true" class="fe icon_pause_alt"></i> fe icon_pause_alt</li>
    <li><i aria-hidden="true" class="fe icon_phone"></i> fe icon_phone</li>
    <li><i aria-hidden="true" class="fe icon_upload"></i> fe icon_upload</li>
    <li><i aria-hidden="true" class="fe icon_download"></i> fe icon_download</li>
    <li><i aria-hidden="true" class="fe icon_rook"></i> fe icon_rook</li>
    <li><i aria-hidden="true" class="fe icon_printer-alt"></i> fe icon_printer-alt</li>
    <li><i aria-hidden="true" class="fe icon_calculator_alt"></i> fe icon_calculator_alt</li>
    <li><i aria-hidden="true" class="fe icon_building_alt"></i> fe icon_building_alt</li>
    <li><i aria-hidden="true" class="fe icon_floppy_alt"></i> fe icon_floppy_alt</li>
    <li><i aria-hidden="true" class="fe icon_drive_alt"></i> fe icon_drive_alt</li>
    <li><i aria-hidden="true" class="fe icon_search_alt"></i> fe icon_search_alt</li>
    <li><i aria-hidden="true" class="fe icon_id_alt"></i> fe icon_id_alt</li>
    <li><i aria-hidden="true" class="fe icon_id-2_alt"></i> fe icon_id-2_alt</li>
    <li><i aria-hidden="true" class="fe icon_puzzle_alt"></i> fe icon_puzzle_alt</li>
    <li><i aria-hidden="true" class="fe icon_like_alt"></i> fe icon_like_alt</li>
    <li><i aria-hidden="true" class="fe icon_dislike_alt"></i> fe icon_dislike_alt</li>
    <li><i aria-hidden="true" class="fe icon_mug_alt"></i> fe icon_mug_alt</li>
    <li><i aria-hidden="true" class="fe icon_currency_alt"></i> fe icon_currency_alt</li>
    <li><i aria-hidden="true" class="fe icon_wallet_alt"></i> fe icon_wallet_alt</li>
    <li><i aria-hidden="true" class="fe icon_pens_alt"></i> fe icon_pens_alt</li>
    <li><i aria-hidden="true" class="fe icon_easel_alt"></i> fe icon_easel_alt</li>
    <li><i aria-hidden="true" class="fe icon_flowchart_alt"></i> fe icon_flowchart_alt</li>
    <li><i aria-hidden="true" class="fe icon_datareport_alt"></i> fe icon_datareport_alt</li>
    <li><i aria-hidden="true" class="fe icon_briefcase_alt"></i> fe icon_briefcase_alt</li>
    <li><i aria-hidden="true" class="fe icon_shield_alt"></i> fe icon_shield_alt</li>
    <li><i aria-hidden="true" class="fe icon_percent_alt"></i> fe icon_percent_alt</li>
    <li><i aria-hidden="true" class="fe icon_globe_alt"></i> fe icon_globe_alt</li>
    <li><i aria-hidden="true" class="fe icon_clipboard"></i> fe icon_clipboard</li>
</ul>

<h2>Social / Brand Icons</h2>
<ul class="fe-icons">
    <li><i aria-hidden="true" class="fe social_facebook"></i> fe social_facebook</li>
    <li><i aria-hidden="true" class="fe social_twitter"></i> fe social_twitter</li>
    <li><i aria-hidden="true" class="fe social_pinterest"></i> fe social_pinterest</li>
    <li><i aria-hidden="true" class="fe social_googleplus"></i> fe social_googleplus</li>
    <li><i aria-hidden="true" class="fe social_tumblr"></i> fe social_tumblr</li>
    <li><i aria-hidden="true" class="fe social_tumbleupon"></i> fe social_tumbleupon</li>
    <li><i aria-hidden="true" class="fe social_wordpress"></i> fe social_wordpress</li>
    <li><i aria-hidden="true" class="fe social_instagram"></i> fe social_instagram</li>
    <li><i aria-hidden="true" class="fe social_dribbble"></i> fe social_dribbble</li>
    <li><i aria-hidden="true" class="fe social_vimeo"></i> fe social_vimeo</li>
    <li><i aria-hidden="true" class="fe social_linkedin"></i> fe social_linkedin</li>
    <li><i aria-hidden="true" class="fe social_rss"></i> fe social_rss</li>
    <li><i aria-hidden="true" class="fe social_deviantart"></i> fe social_deviantart</li>
    <li><i aria-hidden="true" class="fe social_share"></i> fe social_share</li>
    <li><i aria-hidden="true" class="fe social_myspace"></i> fe social_myspace</li>
    <li><i aria-hidden="true" class="fe social_skype"></i> fe social_skype</li>
    <li><i aria-hidden="true" class="fe social_youtube"></i> fe social_youtube</li>
    <li><i aria-hidden="true" class="fe social_picassa"></i> fe social_picassa</li>
    <li><i aria-hidden="true" class="fe social_googledrive"></i> fe social_googledrive</li>
    <li><i aria-hidden="true" class="fe social_flickr"></i> fe social_flickr</li>
    <li><i aria-hidden="true" class="fe social_blogger"></i> fe social_blogger</li>
    <li><i aria-hidden="true" class="fe social_spotify"></i> fe social_spotify</li>
    <li><i aria-hidden="true" class="fe social_delicious"></i> fe social_delicious</li>
    <li><i aria-hidden="true" class="fe social_facebook_circle"></i> fe social_facebook_circle</li>
    <li><i aria-hidden="true" class="fe social_twitter_circle"></i> fe social_twitter_circle</li>
    <li><i aria-hidden="true" class="fe social_pinterest_circle"></i> fe social_pinterest_circle</li>
    <li><i aria-hidden="true" class="fe social_googleplus_circle"></i> fe social_googleplus_circle</li>
    <li><i aria-hidden="true" class="fe social_tumblr_circle"></i> fe social_tumblr_circle</li>
    <li><i aria-hidden="true" class="fe social_stumbleupon_circle"></i> fe social_stumbleupon_circle</li>
    <li><i aria-hidden="true" class="fe social_wordpress_circle"></i> fe social_wordpress_circle</li>
    <li><i aria-hidden="true" class="fe social_instagram_circle"></i> fe social_instagram_circle</li>
    <li><i aria-hidden="true" class="fe social_dribbble_circle"></i> fe social_dribbble_circle</li>
    <li><i aria-hidden="true" class="fe social_vimeo_circle"></i> fe social_vimeo_circle</li>
    <li><i aria-hidden="true" class="fe social_linkedin_circle"></i> fe social_linkedin_circle</li>
    <li><i aria-hidden="true" class="fe social_rss_circle"></i> fe social_rss_circle</li>
    <li><i aria-hidden="true" class="fe social_deviantart_circle"></i> fe social_deviantart_circle</li>
    <li><i aria-hidden="true" class="fe social_share_circle"></i> fe social_share_circle</li>
    <li><i aria-hidden="true" class="fe social_myspace_circle"></i> fe social_myspace_circle</li>
    <li><i aria-hidden="true" class="fe social_skype_circle"></i> fe social_skype_circle</li>
    <li><i aria-hidden="true" class="fe social_youtube_circle"></i> fe social_youtube_circle</li>
    <li><i aria-hidden="true" class="fe social_picassa_circle"></i> fe social_picassa_circle</li>
    <li><i aria-hidden="true" class="fe social_googledrive_alt2"></i> fe social_googledrive_alt2</li>
    <li><i aria-hidden="true" class="fe social_flickr_circle"></i> fe social_flickr_circle</li>
    <li><i aria-hidden="true" class="fe social_blogger_circle"></i> fe social_blogger_circle</li>
    <li><i aria-hidden="true" class="fe social_spotify_circle"></i> fe social_spotify_circle</li>
    <li><i aria-hidden="true" class="fe social_delicious_circle"></i> fe social_delicious_circle</li>
    <li><i aria-hidden="true" class="fe social_facebook_square"></i> fe social_facebook_square</li>
    <li><i aria-hidden="true" class="fe social_twitter_square"></i> fe social_twitter_square</li>
    <li><i aria-hidden="true" class="fe social_pinterest_square"></i> fe social_pinterest_square</li>
    <li><i aria-hidden="true" class="fe social_googleplus_square"></i> fe social_googleplus_square</li>
    <li><i aria-hidden="true" class="fe social_tumblr_square"></i> fe social_tumblr_square</li>
    <li><i aria-hidden="true" class="fe social_stumbleupon_square"></i> fe social_stumbleupon_square</li>
    <li><i aria-hidden="true" class="fe social_wordpress_square"></i> fe social_wordpress_square</li>
    <li><i aria-hidden="true" class="fe social_instagram_square"></i> fe social_instagram_square</li>
    <li><i aria-hidden="true" class="fe social_dribbble_square"></i> fe social_dribbble_square</li>
    <li><i aria-hidden="true" class="fe social_vimeo_square"></i> fe social_vimeo_square</li>
    <li><i aria-hidden="true" class="fe social_linkedin_square"></i> fe social_linkedin_square</li>
    <li><i aria-hidden="true" class="fe social_rss_square"></i> fe social_rss_square</li>
    <li><i aria-hidden="true" class="fe social_deviantart_square"></i> fe social_deviantart_square</li>
    <li><i aria-hidden="true" class="fe social_share_square"></i> fe social_share_square</li>
    <li><i aria-hidden="true" class="fe social_myspace_square"></i> fe social_myspace_square</li>
    <li><i aria-hidden="true" class="fe social_skype_square"></i> fe social_skype_square</li>
    <li><i aria-hidden="true" class="fe social_youtube_square"></i> fe social_youtube_square</li>
    <li><i aria-hidden="true" class="fe social_picassa_square"></i> fe social_picassa_square</li>
    <li><i aria-hidden="true" class="fe social_googledrive_square"></i> fe social_googledrive_square</li>
    <li><i aria-hidden="true" class="fe social_flickr_square"></i> fe social_flickr_square</li>
    <li><i aria-hidden="true" class="fe social_blogger_square"></i> fe social_blogger_square</li>
    <li><i aria-hidden="true" class="fe social_spotify_square"></i> fe social_spotify_square</li>
    <li><i aria-hidden="true" class="fe social_delicious_square"></i> fe social_delicious_square</li>
</ul>
